name: react vite + react 项目
on: push
permissions:
    contents: write

jobs:
    job1:
        runs-on: windows-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Build page
              run: cd ./webapp && npm install && npm run build && cd ..
            - name: Build electron
              run: npm install && node_modules/.bin/electron-rebuild && npm run build && ls dist
            - name: Upload build artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: build-artifacts
                  path: ./dist
                  
    download-artifacts:
        runs-on: windows-latest
        needs: job1
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Download build artifacts
              uses: actions/download-artifact@v3
              with:
                  name: build-artifacts
                  path: ./downloaded-artifacts
